### ISSUE TITLE
SongPlayer.previous

### ISSUE THREAD

**Issue by SageBeard** [SageBeard/bloc-jams-angular#3]
I've created the SongPlayer.previous function to enable seeking previous songs through the player bar. However when I click the previous button, the song is instead pausing.  The console is returning "TypeError: Cannot set property 'playing' of null" for line 85:  SongPlayer.currentSong.playing = null.  

Is the function not recognizing my currentSongIndex? 

I also have the entire checkpoint pushed here: https://github.com/SageBeard/bloc-jams-angular/tree/chkpt-8-services

```javascript
SongPlayer.previous = function() {
       var currentSongIndex = getSongIndex(SongPlayer.currentSong);
       currentSongIndex--;

      if (currentSongIndex < 0) {
         currentBuzzObject.stop();
         SongPlayer.currentSong.playing = null;
       } else {
         var song = currentAlbum.songs[currentSongIndex];
         setSong(song);
         playSong(song);
       }
  };

```

**Comment by bdougie** [comment]
Based on the error this is the problem: `Cannot set property 'playing'`

You are doing this on line 85, which is fine:
```js
SongPlayer.currentSong.playing = null;
```

This is a bit of a red herring. Your real issue is line 21:
```js
    SongPlayer.currentSong = null;

```

Remove that and replace every instance of `currentSong` with `SongPlayer.currentSong` (Line 33 and 41)
