### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by SageBeard** [SageBeard/bloc-jams-angular#5]
I'm confused on assignment 10, adding volume control to my bloc jams. 
Am I setting up my SongPlayer.volume attribute & SongPlayer.setVolume method correctly below? 
Then for the value & max attributes added to the directive, do I need to add an on-change as well? 

````javascript
    SongPlayer.volume = function() {
      if (currentBuzzObject) {
        currentBuzzObject.setVolume();
      }
    };
````

**Comment by bdougie** [comment]
1. Yes you will need an on-change attribute.
```js
on-change="songplayer.volume(value)"
```

2. You function needs to take an argument called value
3. That value will need to be pass to the currentBuzzObject's setVolume function.

**Comment by SageBeard** [comment]
Do I need to pass in the value argument inside the volume function?
````function
SongPlayer.volume = function(value) {
      if (currentBuzzObject) {
        currentBuzzObject.setVolume(value);
      }
    };
`````
Not sure if I'm understanding the attributes correctly...how do I set the max volume number?
````HTML
 <seek-bar value="{{ playerBar.songPlayer.volume }}" max="{{ playerBar.songPlayer.volume(100)}}" on-change="playerBar.songPlayer.volume(value)"></seek-bar>
````

**Comment by bdougie** [comment]
1. Yes, your value argument is correct. 

2. Your notifyOnChange function is failing on line 51 of seekBar.js

```js
angular.js:13708TypeError: notifyOnChange is not a function
    at seekBar.js:61
    at m.$eval (angular.js:17444)
    at m.$apply (angular.js:17544)
    at HTMLDocument.<anonymous> (seekBar.js:59)
    at HTMLDocument.dispatch (jquery-2.1.4.min.js:3)
    at HTMLDocument.r.handle (jquery-2.1.4.min.js:3)
```

3. Setting the max should just be `max="100"`. 

There is an issue with your seekBar directive where you are passing the function as a variable as well. `on-change` should be a function and `value` should be a value. 

Try making the volume function `setVolume` and creating a separate volume attribute

```js
SongPlayer.volume = null;

... 

SongPlayer.setVolume = function(value) {
      if (currentBuzzObject) {
         SongPlayer.volume = currentBuzzObject.setVolume(value);
      }
 };
```

```html
 <seek-bar value="{{ playerBar.songPlayer.volume }}" max="100" on-change="playerBar.songPlayer.setVolume(value)"></seek-bar>

```

**Comment by bdougie** [comment]
I opened a PR that fixes the volume. Per my change what do you think the issue was? https://github.com/SageBeard/bloc-jams-angular/pull/6/files
